//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientInformation
    {
        public int Id { get; set; }
        public string pushEndpoint { get; set; }
        public string p256dh { get; set; }
        public string auth { get; set; }
    }
}
